# Lab | Web Scraping

Welcome to the "Books to Scrape" Web Scraping Adventure Lab!

**Objective**

In this lab, we will embark on a mission to unearth valuable insights from the data available on Books to Scrape, an online platform showcasing a wide variety of books. As data analyst, you have been tasked with scraping a specific subset of book data from Books to Scrape to assist publishing companies in understanding the landscape of highly-rated books across different genres. Your insights will help shape future book marketing strategies and publishing decisions.

**Background**

In a world where data has become the new currency, businesses are leveraging big data to make informed decisions that drive success and profitability. The publishing industry, much like others, utilizes data analytics to understand market trends, reader preferences, and the performance of books based on factors such as genre, author, and ratings. Books to Scrape serves as a rich source of such data, offering detailed information about a diverse range of books, making it an ideal platform for extracting insights to aid in informed decision-making within the literary world.

**Task**

Your task is to create a Python script using BeautifulSoup and pandas to scrape Books to Scrape book data, focusing on book ratings and genres. The script should be able to filter books with ratings above a certain threshold and in specific genres. Additionally, the script should structure the scraped data in a tabular format using pandas for further analysis.

**Expected Outcome**

A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`. The function should scrape book data from the "Books to Scrape" website and return a `pandas` DataFrame with the following columns:

**Expected Outcome**

- A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`.
- The function should return a DataFrame with the following columns:
  - **UPC**: The Universal Product Code (UPC) of the book.
  - **Title**: The title of the book.
  - **Price (£)**: The price of the book in pounds.
  - **Rating**: The rating of the book (1-5 stars).
  - **Genre**: The genre of the book.
  - **Availability**: Whether the book is in stock or not.
  - **Description**: A brief description or product description of the book (if available).
  
You will execute this script to scrape data for books with a minimum rating of `4.0 and above` and a maximum price of `£20`. 

Remember to experiment with different ratings and prices to ensure your code is versatile and can handle various searches effectively!

**Resources**

- [Beautiful Soup Documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- [Pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/index.html)
- [Books to Scrape](https://books.toscrape.com/)

**Hint**

Your first mission is to familiarize yourself with the **Books to Scrape** website. Navigate to [Books to Scrape](http://books.toscrape.com/) and explore the available books to understand their layout and structure. 

Next, think about how you can set parameters for your data extraction:

- **Minimum Rating**: Focus on books with a rating of 4.0 and above.
- **Maximum Price**: Filter for books priced up to £20.

After reviewing the site, you can construct a plan for scraping relevant data. Pay attention to the details displayed for each book, including the title, price, rating, and availability. This will help you identify the correct HTML elements to target with your scraping script.

Make sure to build your scraping URL and logic based on the patterns you observe in the HTML structure of the book listings!


---

**Best of luck! Immerse yourself in the world of books, and may the data be with you!**

**Important Note**:

In the fast-changing online world, websites often update and change their structures. When you try this lab, the **Books to Scrape** website might differ from what you expect.

If you encounter issues due to these changes, like new rules or obstacles preventing data extraction, don’t worry! Get creative.

You can choose another website that interests you and is suitable for scraping data. Options like Wikipedia, The New York Times, or even library databases are great alternatives. The main goal remains the same: extract useful data and enhance your web scraping skills while exploring a source of information you enjoy. This is your opportunity to practice and adapt to different web environments!

In [1]:
# Your solution goes here
# ============================================================
# IMPORTS
# English: We import the three libraries we need:
#   - requests   → makes HTTP GET requests (downloads the HTML page)
#   - BeautifulSoup → parses HTML so we can search and extract data
#   - pandas     → organises the extracted data into a table (DataFrame)
#
# Español: Importamos las tres librerías necesarias:
#   - requests   → hace peticiones HTTP GET (descarga la página HTML)
#   - BeautifulSoup → analiza el HTML para buscar y extraer datos
#   - pandas     → organiza los datos extraídos en una tabla (DataFrame)
# ============================================================

import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
# ============================================================
# STEP 1 – Download the first catalogue page
# English:
#   We build the URL for page 1 of the catalogue.
#   requests.get() downloads the raw HTML of that page.
#   We check the status code: 200 = success, anything else = problem.
#
# Español:
#   Construimos la URL de la página 1 del catálogo.
#   requests.get() descarga el HTML crudo de esa página.
#   Comprobamos el código de estado: 200 = éxito, otro valor = problema.
# ============================================================

base_url = "https://books.toscrape.com/catalogue/"
url = base_url + "page-1.html"

response = requests.get(url)
print("HTTP Status:", response.status_code)  # 200 = OK

HTTP Status: 200

In [3]:
# ============================================================
# STEP 2 – Parse the HTML with BeautifulSoup
# English:
#   BeautifulSoup receives the raw bytes (response.content) and
#   the parser name ("html.parser" is built into Python, no install needed).
#   It creates a tree-like object we can search with methods like .find().
#
# Español:
#   BeautifulSoup recibe los bytes crudos (response.content) y
#   el nombre del parser ("html.parser" viene incluido en Python).
#   Crea un objeto en forma de árbol que podemos buscar con .find().
# ============================================================

soup = BeautifulSoup(response.content, "html.parser")

# Look at ONE book card to understand the HTML structure
# Observar UNA tarjeta de libro para entender la estructura HTML
first_book = soup.find("article", class_="product_pod")
print(first_book.prettify())

<article class="product_pod">
 <div class="image_container">
  <a href="a-light-in-the-attic_1000/index.html">
   <img alt="A Light in the Attic" class="thumbnail" src="../media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>
  </a>
 </div>
 <p class="star-rating Three">
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
 </p>
 <h3>
  <a href="a-light-in-the-attic_1000/index.html" title="A Light in the Attic">
   A Light in the ...
  </a>
 </h3>
 <div class="product_price">
  <p class="price_color">
   £51.77
  </p>
  <p class="instock availability">
   <i class="icon-ok">
   </i>
   In stock
  </p>
  <form>
   <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
    Add to basket
   </button>
  </form>
 </div>
</article>

In [4]:
# ============================================================
# HELPER 1 – Convert word rating to number
# English:
#   The website stores ratings as CSS class names: "One", "Two", ..., "Five".
#   We need to convert those words to integers (1, 2, 3, 4, 5) so we can
#   compare them with the min_rating parameter.
#
# Español:
#   El sitio almacena los ratings como clases CSS: "One", "Two", ..., "Five".
#   Necesitamos convertir esas palabras a enteros (1, 2, 3, 4, 5) para poder
#   compararlos con el parámetro min_rating.
# ============================================================

def word_to_rating(word):
    """
    Converts a word rating (e.g. 'Four') to an integer (e.g. 4).
    Convierte un rating en palabras (ej. 'Four') a un entero (ej. 4).
    """
    rating_map = {
        "One": 1,
        "Two": 2,
        "Three": 3,
        "Four": 4,
        "Five": 5
    }
    # .get() returns 0 if the word is not found, avoiding errors
    # .get() devuelve 0 si la palabra no existe, evitando errores
    return rating_map.get(word, 0)


# Quick test / Prueba rápida
print(word_to_rating("Four"))   # Expected: 4
print(word_to_rating("One"))    # Expected: 1

4
1

In [5]:
# ============================================================
# HELPER 2 – Scrape the detail page of a single book
# English:
#   The listing page only shows title, price, rating, and availability.
#   Genre, UPC, and Description are only available on each book's own page.
#   This function downloads a book detail page and extracts those extra fields.
#
# Español:
#   La página de listado sólo muestra título, precio, rating y disponibilidad.
#   El género, UPC y descripción solo están en la página individual del libro.
#   Esta función descarga esa página y extrae esos campos adicionales.
# ============================================================

def get_book_details(detail_url):
    """
    Downloads a book's detail page and returns a dict with:
    UPC, Genre, Description.

    Descarga la página de detalle de un libro y devuelve un dict con:
    UPC, Género, Descripción.
    """
    response = requests.get(detail_url)
    soup = BeautifulSoup(response.content, "html.parser")

    # ---- UPC ----
    # English: The UPC is inside a <table> with class "table table-striped".
    #          Each row has <th> (label) and <td> (value). We look for "UPC".
    # Español: El UPC está dentro de una <table class="table table-striped">.
    #          Cada fila tiene <th> (etiqueta) y <td> (valor). Buscamos "UPC".
    upc = "N/A"  # default if not found / valor por defecto si no se encuentra
    table = soup.find("table", class_="table table-striped")
    if table:
        rows = table.find_all("tr")
        for row in rows:
            header = row.find("th")
            value  = row.find("td")
            if header and value and header.text.strip() == "UPC":
                upc = value.text.strip()
                break  # stop once found / detenemos cuando lo encontramos

    # ---- GENRE ----
    # English: The genre appears in the breadcrumb navigation at the top of the page.
    #          Breadcrumb looks like: Home > Mystery > [Book Title]
    #          Genre is the THIRD element (index 2) of the breadcrumb list.
    # Español: El género aparece en el breadcrumb (miga de pan) de la página.
    #          El breadcrumb es: Home > Misterio > [Título del libro]
    #          El género es el TERCER elemento (índice 2) de esa lista.
    genre = "N/A"
    breadcrumb = soup.find("ul", class_="breadcrumb")
    if breadcrumb:
        items = breadcrumb.find_all("li")
        if len(items) >= 3:
            genre = items[2].text.strip()  # index 0=Home, 1=Books, 2=Genre, 3=Title

    # ---- DESCRIPTION ----
    # English: The description is inside the first <p> tag that comes after
    #          the <div id="product_description"> element.
    #          Some books have no description, so we use a fallback.
    # Español: La descripción está dentro del primer <p> que sigue al
    #          elemento <div id="product_description">.
    #          Algunos libros no tienen descripción, así que usamos un valor por defecto.
    description = "No description available"
    desc_header = soup.find("div", id="product_description")
    if desc_header:
        next_p = desc_header.find_next_sibling("p")
        if next_p:
            description = next_p.text.strip()

    return {
        "UPC": upc,
        "Genre": genre,
        "Description": description
    }


# Quick test with a known book
# Prueba rápida con un libro conocido
test_details = get_book_details("https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html")
print(test_details)

{'UPC': 'a897fe39b1053632', 'Genre': 'Poetry', 'Description': "It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love th It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love that Silverstein. Need proof of his genius? RockabyeRockabye baby, in the treetopDon't you know a treetopIs no safe place to rock?And who put you up there,And your cradle, too?Baby, I think someone down here'sGot it in for you. Shel, you never sounded so good. ...more"}

In [6]:
# ============================================================
# MAIN FUNCTION – scrape_books
# English:
#   This function iterates through ALL pages of the Books to Scrape catalogue.
#   For each book on each page it:
#     1. Extracts title, price, rating, availability from the listing card.
#     2. Applies the min_rating and max_price filters immediately.
#        → If a book fails either filter, we SKIP it (no detail page request)
#          This avoids making hundreds of unnecessary HTTP requests.
#     3. Only visits the detail page for books that PASS both filters.
#     4. Collects all data into a list, then converts it to a DataFrame.
#
# Español:
#   Esta función recorre TODAS las páginas del catálogo de Books to Scrape.
#   Para cada libro en cada página:
#     1. Extrae título, precio, rating y disponibilidad de la tarjeta del listado.
#     2. Aplica los filtros min_rating y max_price de inmediato.
#        → Si un libro no pasa algún filtro, lo SALTAMOS (sin petición de detalle)
#          Esto evita cientos de peticiones HTTP innecesarias.
#     3. Sólo visita la página de detalle para libros que PASAN ambos filtros.
#     4. Recopila todos los datos en una lista y la convierte en DataFrame.
# ============================================================

def scrape_books(min_rating, max_price):
    """
    Scrapes books.toscrape.com and returns a DataFrame of books
    that satisfy both conditions:
      - Rating  >= min_rating  (integer 1-5)
      - Price   <= max_price   (float, in GBP £)

    Parameters / Parámetros:
      min_rating (int/float) : minimum star rating (1–5)
      max_price  (float)     : maximum price in pounds

    Returns / Devuelve:
      pandas.DataFrame with columns:
        UPC, Title, Price (£), Rating, Genre, Availability, Description
    """

    # ---------------------------------------------------------
    # Base URL for the catalogue pages
    # URL base para las páginas del catálogo
    # ---------------------------------------------------------
    base_url = "https://books.toscrape.com/catalogue/"

    # List that will hold one dict per book that passes the filters
    # Lista que guardará un dict por libro que pase los filtros
    books_data = []

    # Start from page 1 and keep going until there are no more pages
    # Empezamos desde la página 1 y continuamos hasta que no haya más
    page_number = 1

    while True:  # We'll break out of this loop when we run out of pages

        # ---- Build the page URL ----
        # Construir la URL de la página actual
        page_url = base_url + f"page-{page_number}.html"
        response = requests.get(page_url)

        # ---- Stop if page doesn't exist ----
        # English: A 404 status means the page doesn't exist → we've gone past the last page.
        # Español: Un código 404 significa que la página no existe → pasamos de la última.
        if response.status_code == 404:
            print(f"  → No more pages after page {page_number - 1}. Stopping.")
            break

        print(f"Scraping page {page_number}...")

        # Parse the HTML of the current listing page
        # Parsear el HTML de la página de listado actual
        soup = BeautifulSoup(response.content, "html.parser")

        # Find all book cards on this page
        # English: Every book is wrapped in an <article class="product_pod"> tag.
        # Español: Cada libro está envuelto en una etiqueta <article class="product_pod">.
        book_cards = soup.find_all("article", class_="product_pod")

        # ---- Loop through each book card on the page ----
        # Recorrer cada tarjeta de libro en la página
        for card in book_cards:

            # == EXTRACT RATING ==
            # English: The rating is a CSS class on the <p class="star-rating Four"> element.
            #          We grab the SECOND class (index 1) — the first is always "star-rating".
            # Español: El rating es una clase CSS en <p class="star-rating Four">.
            #          Tomamos la SEGUNDA clase (índice 1) — la primera siempre es "star-rating".
            rating_tag = card.find("p", class_="star-rating")
            rating_word = rating_tag["class"][1]   # e.g. "Four"
            rating = word_to_rating(rating_word)    # e.g. 4

            # == FILTER BY RATING (early exit) ==
            # English: If the rating is below our minimum, skip this book immediately.
            #          This avoids loading the detail page unnecessarily.
            # Español: Si el rating es menor que el mínimo, saltamos este libro.
            #          Así evitamos cargar la página de detalle innecesariamente.
            if rating < min_rating:
                continue  # go to next book / ir al siguiente libro

            # == EXTRACT PRICE ==
            # English: Price is inside <p class="price_color"> as text like "£12.50".
            #          We strip the "£" symbol and convert to float for comparison.
            # Español: El precio está en <p class="price_color"> como texto "£12.50".
            #          Quitamos el símbolo "£" y convertimos a float para comparar.
            price_text = card.find("p", class_="price_color").text.strip()
            price = float(price_text.replace("£", "").strip())

            # == FILTER BY PRICE (early exit) ==
            # If price exceeds maximum, skip this book
            # Si el precio supera el máximo, saltamos este libro
            if price > max_price:
                continue

            # == EXTRACT TITLE ==
            # English: Title is in the "title" attribute of the <a> inside <h3>.
            #          (The visible text is truncated; the attribute has the full title.)
            # Español: El título está en el atributo "title" del <a> dentro del <h3>.
            #          (El texto visible está truncado; el atributo tiene el título completo.)
            title = card.find("h3").find("a")["title"]

            # == EXTRACT AVAILABILITY ==
            # English: Availability text is inside <p class="instock availability">.
            #          We use .strip() to remove extra whitespace.
            # Español: La disponibilidad está en <p class="instock availability">.
            #          Usamos .strip() para eliminar espacios en blanco extra.
            availability_tag = card.find("p", class_="availability")
            availability = availability_tag.text.strip()

            # == BUILD DETAIL PAGE URL ==
            # English: The href in each card looks like "../../../some-book/index.html".
            #          We replace the "../../../" prefix with our base_url to get the full URL.
            # Español: El href en cada tarjeta tiene la forma "../../../some-book/index.html".
            #          Reemplazamos el prefijo "../../../" con base_url para obtener la URL completa.
            relative_link = card.find("h3").find("a")["href"]
            detail_url = base_url + relative_link.replace("../", "")

            # == FETCH DETAIL PAGE (UPC, Genre, Description) ==
            # Only called for books that passed BOTH filters
            # Solo se llama para libros que pasaron AMBOS filtros
            details = get_book_details(detail_url)

            # == APPEND BOOK RECORD ==
            # English: Build a dictionary with ALL required columns and add it to our list.
            # Español: Construimos un diccionario con TODAS las columnas requeridas y lo añadimos.
            books_data.append({
                "UPC":          details["UPC"],
                "Title":        title,
                "Price (£)":    price,
                "Rating":       rating,
                "Genre":        details["Genre"],
                "Availability": availability,
                "Description":  details["Description"]
            })

        # Move to the next page / Pasar a la siguiente página
        page_number += 1

    # ---- Build and return the DataFrame ----
    # English: Convert our list of dicts to a pandas DataFrame.
    #          reset_index(drop=True) gives clean sequential indices (0, 1, 2, ...).
    # Español: Convertimos nuestra lista de dicts en un DataFrame de pandas.
    #          reset_index(drop=True) da índices secuenciales limpios (0, 1, 2, ...).
    df = pd.DataFrame(books_data)
    df = df.reset_index(drop=True)
    return df

In [7]:
# ============================================================
# RUN THE SCRAPER
# English:
#   We call scrape_books with the parameters from the lab instructions.
#   This will take a few minutes because it visits hundreds of pages.
#   You will see progress printed for each page.
#
# Español:
#   Llamamos a scrape_books con los parámetros indicados en el enunciado.
#   Tardará unos minutos porque visita cientos de páginas.
#   Verás el progreso impreso en cada página.
# ============================================================

df = scrape_books(min_rating=4, max_price=20)

print(f"\n✅ Done! Found {len(df)} books matching the criteria.")
print(f"✅ ¡Listo! Se encontraron {len(df)} libros que cumplen los criterios.")

Scraping page 1...
Scraping page 2...
Scraping page 3...
Scraping page 4...
Scraping page 5...
Scraping page 6...
Scraping page 7...
Scraping page 8...
Scraping page 9...
Scraping page 10...
Scraping page 11...
Scraping page 12...
Scraping page 13...
Scraping page 14...
Scraping page 15...
Scraping page 16...
Scraping page 17...
Scraping page 18...
Scraping page 19...
Scraping page 20...
Scraping page 21...
Scraping page 22...
Scraping page 23...
Scraping page 24...
Scraping page 25...
Scraping page 26...
Scraping page 27...
Scraping page 28...
Scraping page 29...
Scraping page 30...
Scraping page 31...
Scraping page 32...
Scraping page 33...
Scraping page 34...
Scraping page 35...
Scraping page 36...
Scraping page 37...
Scraping page 38...
Scraping page 39...
Scraping page 40...
Scraping page 41...
Scraping page 42...
Scraping page 43...
Scraping page 44...
Scraping page 45...
Scraping page 46...
Scraping page 47...
Scraping page 48...
Scraping page 49...
Scraping page 50...
  → No more pages after page 50. Stopping.

✅ Done! Found 75 books matching the criteria.
✅ ¡Listo! Se encontraron 75 libros que cumplen los criterios.

In [8]:
df.head()

,UPC,Title,Price (£),Rating,Genre,Availability,Description
0,ce6396b0f23f6ecc,Set Me Free,17.46,5,Young Adult,In stock,Aaron Ledbetter’s future had been planned out ...
1,6258a1f6a6dcfe50,The Four Agreements: A Practical Guide to Pers...,17.66,5,Spirituality,In stock,"In The Four Agreements, don Miguel Ruiz reveal..."
2,6be3beb0793a53e7,Sophie's World,15.94,5,Philosophy,In stock,A page-turning novel that is also an explorati...
3,657fe5ead67a7767,Untitled Collection: Sabbath Poems 2014,14.27,4,Poetry,In stock,"More than thirty-five years ago, when the weat..."
4,51653ef291ab7ddc,This One Summer,19.49,4,Sequential Art,In stock,"Every summer, Rose goes with her mom and dad t..."

In [9]:
# ============================================================
# DATA OVERVIEW
# English: .info() shows column names, data types, and non-null counts.
#          This helps us verify everything was scraped correctly.
# Español: .info() muestra nombres de columnas, tipos de datos y conteo de no-nulos.
#          Esto nos ayuda a verificar que todo se extrajo correctamente.
# ============================================================

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   UPC           75 non-null     str
 1   Title         75 non-null     str
 2   Price (£)     75 non-null     float64
 3   Rating        75 non-null     int64
 4   Genre         75 non-null     str
 5   Availability  75 non-null     str
 6   Description   75 non-null     str
dtypes: float64(1), int64(1), str(5)
memory usage: 106.4 KB

In [10]:

print("Books per Genre / Libros por Género:")
print(df["Genre"].value_counts())

Books per Genre / Libros por Género:
Genre
Default               10
Sequential Art         9
Young Adult            7
Nonfiction             6
Fiction                5
Poetry                 4
Food and Drink         4
Fantasy                3
Romance                3
Philosophy             2
Childrens              2
Humor                  2
Add a comment          2
Science                2
Womens Fiction         2
Spirituality           1
Business               1
Erotica                1
Art                    1
Christian Fiction      1
Classics               1
Horror                 1
Autobiography          1
Science Fiction        1
Adult Fiction          1
Mystery                1
Historical Fiction     1
Name: count, dtype: int64

In [11]:

print("=== Experiment 1: 5-star books under £15 ===")
df_five_stars = scrape_books(min_rating=5, max_price=15)
print(f"Found {len(df_five_stars)} books")
df_five_stars.head(3)
print("=== Experiment 2: 3+ star books under £10 ===")
df_budget = scrape_books(min_rating=3, max_price=10)
print(f"Found {len(df_budget)} books")
df_budget.head(3)

=== Experiment 1: 5-star books under £15 ===
Scraping page 1...
Scraping page 2...
Scraping page 3...
Scraping page 4...
Scraping page 5...
Scraping page 6...
Scraping page 7...
Scraping page 8...
Scraping page 9...
Scraping page 10...
Scraping page 11...
Scraping page 12...
Scraping page 13...
Scraping page 14...
Scraping page 15...
Scraping page 16...
Scraping page 17...
Scraping page 18...
Scraping page 19...
Scraping page 20...
Scraping page 21...
Scraping page 22...
Scraping page 23...
Scraping page 24...
Scraping page 25...
Scraping page 26...
Scraping page 27...
Scraping page 28...
Scraping page 29...
Scraping page 30...
Scraping page 31...
Scraping page 32...
Scraping page 33...
Scraping page 34...
Scraping page 35...
Scraping page 36...
Scraping page 37...
Scraping page 38...
Scraping page 39...
Scraping page 40...
Scraping page 41...
Scraping page 42...
Scraping page 43...
Scraping page 44...
Scraping page 45...
Scraping page 46...
Scraping page 47...
Scraping page 48...
Scraping page 49...
Scraping page 50...
  → No more pages after page 50. Stopping.
Found 23 books
=== Experiment 2: 3+ star books under £10 ===
Scraping page 1...
Scraping page 2...
Scraping page 3...
Scraping page 4...
Scraping page 5...
Scraping page 6...
Scraping page 7...
Scraping page 8...
Scraping page 9...
Scraping page 10...
Scraping page 11...
Scraping page 12...
Scraping page 13...
Scraping page 14...
Scraping page 15...
Scraping page 16...
Scraping page 17...
Scraping page 18...
Scraping page 19...
Scraping page 20...
Scraping page 21...
Scraping page 22...
Scraping page 23...
Scraping page 24...
Scraping page 25...
Scraping page 26...
Scraping page 27...
Scraping page 28...
Scraping page 29...
Scraping page 30...
Scraping page 31...
Scraping page 32...
Scraping page 33...
Scraping page 34...
Scraping page 35...
Scraping page 36...
Scraping page 37...
Scraping page 38...
Scraping page 39...
Scraping page 40...
Scraping page 41...
Scraping page 42...
Scraping page 43...
Scraping page 44...
Scraping page 45...
Scraping page 46...
Scraping page 47...
Scraping page 48...
Scraping page 49...
Scraping page 50...
  → No more pages after page 50. Stopping.
Found 1 books

,UPC,Title,Price (£),Rating,Genre,Availability,Description
0,f36d24c309e87e5b,An Abundance of Katherines,10.0,5,Young Adult,In stock,Katherine V thought boys were gross Katherine ...